name: build

on:
  release:
    types: [published]

jobs:
  build:
    name: "Ubuntu ${{ matrix.os }}: ${{ matrix.ghc }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 20.04
            ghc: "8.10.7"
            platform_name: 20_04-x86-64
          - os: 22.04
            ghc: "9.6.3"
            platform_name: 22_04-x86-64
          - os: 24.04
            ghc: "9.6.3"
            platform_name: 24_04-x86-64
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Build and test
        shell: bash
        run: docker build --output . .

      - name: Prepare binaries--output . .
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          mv smp-server smp-server-ubuntu-${{ matrix.platform_name}}
          mv ntf-server ntf-server-ubuntu-${{ matrix.platform_name}}
          mv xftp-server xftp-server-ubuntu-${{ matrix.platform_name}}
          mv xftp xftp-ubuntu-${{ matrix.platform_name}}

      - name: Build changelog
        if: startsWith(github.ref, 'refs/tags/v')
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/changelog_conf.json
          failOnError: true
          ignorePreReleases: true
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.ghc != '8.10.7'
        uses: softprops/action-gh-release@v2
        with:
          body: |
            See full changelog [here](https://github.com/simplex-chat/simplexmq/blob/master/CHANGELOG.md).

            Commits:
            ${{ steps.build_changelog.outputs.changelog }}
          prerelease: true
          files: |
            LICENSE
            smp-server-ubuntu-${{ matrix.platform_name}}
            ntf-server-ubuntu-${{ matrix.platform_name}}
            xftp-server-ubuntu-${{ matrix.platform_name}}
            xftp-ubuntu-${{ matrix.platform_name}}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
