name: Reproduce latest release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # every day at 02:00 night

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - name: Execute reproduce script
        run: |
          mkdir -p v6.3.1-fake
          touch v6.3.1-fake/_sha256sums

      - name: Check if build has been reproduced
        env:
          url: ${{ secrets.WEBHOOK_URL }}
          user: ${{ secrets.WEBHOOK_USER }}
          pass: ${{ secrets.WEBHOOK_PASS }}
          TAG: "v6.3.1-fake"
        run: |
          set -x
          if [ -f "${GITHUB_WORKSPACE}/$TAG/_sha256sums" ]; then
            curl -v \
              -u "${user}:${pass}" \
              -H 'Content-Type: application/json' \
              -d '{"title": "👾 GitHub: Runner", "description": "Testing: '"$TAG"' did reproduce."}' \
              "$url"
            exit 0
          else
            curl -v \
              -u "${user}:${pass}" \
              -H 'Content-Type: application/json' \
              -d '{"title": "👾 GitHub: Runner", "description": "⛔️ '"$TAG"' did not reproduce."}' \
              "$url"
            exit 1
          fi
